# Generated by Django 5.0.7 on 2024-07-13 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=250)),
                ('fecha', models.DateTimeField(verbose_name=True)),
                ('hora', models.TimeField(blank=True)),
                ('lugar', models.CharField(max_length=50)),
                ('capacidad_max', models.BooleanField(verbose_name=True)),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.usuarios')),
            ],
        ),
    ]
